language: python
sudo: required
dist: xenial
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

jobs:
  include:
    - stage: check
      script: flake8 --ignore E501 openpyscad

script:
  - nosetests  --with-coverage --cover-package=openpyscad

after_success:
  - coveralls

stages:
  - check
  - test

notifications:
  email: false